image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building... "
    - mvn clean verify

test:
  stage: test
  script:
    - echo "Running tests... "
    - mvn verify serenity:aggregate
    - echo "Tests Completed"
  artifacts:
    when: always
    paths:
      - target
    reports:
      junit:
        - target/report.xml